pipeline{

    agent{
      docker{
        image 'maven:3.6.1-jdk-8-slim'
        args '-v m2cache:/root/.m2'
      }
    }


    stages{
        stage("build"){
            when{
              changeset "**/worker/**"
            }
            steps{
                echo "Building worker app..."
                dir("worker"){
                  sh 'mvn compile'
                }
            }
        }
        stage("test"){
            when{
              changeset "**/worker/**"
            }
            steps{
                echo "Testing worker app..."
                dir("worker"){
                  sh 'mvn clean test'
                }
            }
        }
        stage("package"){
            when{
              changeset "**/worker/**"
              branch 'master'
            }
            steps{
                echo "Packaging worker app..."
                dir("worker"){
                  sh 'mvn package -DskipTests'
                  archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }

    }
    
    post{
        always{
            echo "This pipeline run is completed.."
        }
    }
}
